// clang-format off
// Generated by tools/schema_gen.py from src/db/schema.rb (Rails: db/schema.rb). Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>
#include <optional>
#include <string_view>

#include "db/row.hpp"

namespace campfire::db::schema {

enum class Table : std::uint8_t {
  Accounts,
  ActionTextRichTexts,
  ActiveStorageAttachments,
  ActiveStorageBlobs,
  ActiveStorageVariantRecords,
  Bans,
  Boosts,
  Memberships,
  Messages,
  PushSubscriptions,
  Rooms,
  Searches,
  Sessions,
  Users,
  Webhooks,
};
inline constexpr std::size_t kTableCount = 15;

[[nodiscard]] constexpr std::string_view table_name(Table table) noexcept {
  switch (table) {
    case Table::Accounts: return "accounts";
    case Table::ActionTextRichTexts: return "action_text_rich_texts";
    case Table::ActiveStorageAttachments: return "active_storage_attachments";
    case Table::ActiveStorageBlobs: return "active_storage_blobs";
    case Table::ActiveStorageVariantRecords: return "active_storage_variant_records";
    case Table::Bans: return "bans";
    case Table::Boosts: return "boosts";
    case Table::Memberships: return "memberships";
    case Table::Messages: return "messages";
    case Table::PushSubscriptions: return "push_subscriptions";
    case Table::Rooms: return "rooms";
    case Table::Searches: return "searches";
    case Table::Sessions: return "sessions";
    case Table::Users: return "users";
    case Table::Webhooks: return "webhooks";
  }
  return "";
}

// Table accounts.
struct AccountRow {
  static constexpr Table kTable = Table::Accounts;
  static constexpr std::string_view kTableName = "accounts";
  // The columns to select, in the order that `read` uses.
  static constexpr std::string_view kColumns = "\"accounts\".\"id\", \"accounts\".\"created_at\", \"accounts\".\"custom_styles\", \"accounts\".\"join_code\", \"accounts\".\"name\", \"accounts\".\"settings\", \"accounts\".\"singleton_guard\", \"accounts\".\"updated_at\"";
  static constexpr int kColumnCount = 8;

  std::int64_t id{};
  std::string_view created_at{};
  std::optional<std::string_view> custom_styles{};
  std::string_view join_code{};
  std::string_view name{};
  std::optional<std::string_view> settings{};
  std::int64_t singleton_guard{};
  std::string_view updated_at{};

  [[nodiscard]] static AccountRow read(RowReader& r) {
    AccountRow row;
    row.id = r.i64(0);
    row.created_at = r.text(1);
    row.custom_styles = r.text_opt(2);
    row.join_code = r.text(3);
    row.name = r.text(4);
    row.settings = r.text_opt(5);
    row.singleton_guard = r.i64(6);
    row.updated_at = r.text(7);
    return row;
  }
};

// Table action_text_rich_texts.
struct ActionTextRichTextRow {
  static constexpr Table kTable = Table::ActionTextRichTexts;
  static constexpr std::string_view kTableName = "action_text_rich_texts";
  // The columns to select, in the order that `read` uses.
  static constexpr std::string_view kColumns = "\"action_text_rich_texts\".\"id\", \"action_text_rich_texts\".\"body\", \"action_text_rich_texts\".\"created_at\", \"action_text_rich_texts\".\"name\", \"action_text_rich_texts\".\"record_id\", \"action_text_rich_texts\".\"record_type\", \"action_text_rich_texts\".\"updated_at\"";
  static constexpr int kColumnCount = 7;

  std::int64_t id{};
  std::optional<std::string_view> body{};
  std::string_view created_at{};
  std::string_view name{};
  std::int64_t record_id{};
  std::string_view record_type{};
  std::string_view updated_at{};

  [[nodiscard]] static ActionTextRichTextRow read(RowReader& r) {
    ActionTextRichTextRow row;
    row.id = r.i64(0);
    row.body = r.text_opt(1);
    row.created_at = r.text(2);
    row.name = r.text(3);
    row.record_id = r.i64(4);
    row.record_type = r.text(5);
    row.updated_at = r.text(6);
    return row;
  }
};

// Table active_storage_attachments.
struct ActiveStorageAttachmentRow {
  static constexpr Table kTable = Table::ActiveStorageAttachments;
  static constexpr std::string_view kTableName = "active_storage_attachments";
  // The columns to select, in the order that `read` uses.
  static constexpr std::string_view kColumns = "\"active_storage_attachments\".\"id\", \"active_storage_attachments\".\"blob_id\", \"active_storage_attachments\".\"created_at\", \"active_storage_attachments\".\"name\", \"active_storage_attachments\".\"record_id\", \"active_storage_attachments\".\"record_type\"";
  static constexpr int kColumnCount = 6;

  std::int64_t id{};
  std::int64_t blob_id{};
  std::string_view created_at{};
  std::string_view name{};
  std::int64_t record_id{};
  std::string_view record_type{};

  [[nodiscard]] static ActiveStorageAttachmentRow read(RowReader& r) {
    ActiveStorageAttachmentRow row;
    row.id = r.i64(0);
    row.blob_id = r.i64(1);
    row.created_at = r.text(2);
    row.name = r.text(3);
    row.record_id = r.i64(4);
    row.record_type = r.text(5);
    return row;
  }
};

// Table active_storage_blobs.
struct ActiveStorageBlobRow {
  static constexpr Table kTable = Table::ActiveStorageBlobs;
  static constexpr std::string_view kTableName = "active_storage_blobs";
  // The columns to select, in the order that `read` uses.
  static constexpr std::string_view kColumns = "\"active_storage_blobs\".\"id\", \"active_storage_blobs\".\"byte_size\", \"active_storage_blobs\".\"checksum\", \"active_storage_blobs\".\"content_type\", \"active_storage_blobs\".\"created_at\", \"active_storage_blobs\".\"filename\", \"active_storage_blobs\".\"key\", \"active_storage_blobs\".\"metadata\", \"active_storage_blobs\".\"service_name\"";
  static constexpr int kColumnCount = 9;

  std::int64_t id{};
  std::int64_t byte_size{};
  std::optional<std::string_view> checksum{};
  std::optional<std::string_view> content_type{};
  std::string_view created_at{};
  std::string_view filename{};
  std::string_view key{};
  std::optional<std::string_view> metadata{};
  std::string_view service_name{};

  [[nodiscard]] static ActiveStorageBlobRow read(RowReader& r) {
    ActiveStorageBlobRow row;
    row.id = r.i64(0);
    row.byte_size = r.i64(1);
    row.checksum = r.text_opt(2);
    row.content_type = r.text_opt(3);
    row.created_at = r.text(4);
    row.filename = r.text(5);
    row.key = r.text(6);
    row.metadata = r.text_opt(7);
    row.service_name = r.text(8);
    return row;
  }
};

// Table active_storage_variant_records.
struct ActiveStorageVariantRecordRow {
  static constexpr Table kTable = Table::ActiveStorageVariantRecords;
  static constexpr std::string_view kTableName = "active_storage_variant_records";
  // The columns to select, in the order that `read` uses.
  static constexpr std::string_view kColumns = "\"active_storage_variant_records\".\"id\", \"active_storage_variant_records\".\"blob_id\", \"active_storage_variant_records\".\"variation_digest\"";
  static constexpr int kColumnCount = 3;

  std::int64_t id{};
  std::int64_t blob_id{};
  std::string_view variation_digest{};

  [[nodiscard]] static ActiveStorageVariantRecordRow read(RowReader& r) {
    ActiveStorageVariantRecordRow row;
    row.id = r.i64(0);
    row.blob_id = r.i64(1);
    row.variation_digest = r.text(2);
    return row;
  }
};

// Table bans.
struct BanRow {
  static constexpr Table kTable = Table::Bans;
  static constexpr std::string_view kTableName = "bans";
  // The columns to select, in the order that `read` uses.
  static constexpr std::string_view kColumns = "\"bans\".\"id\", \"bans\".\"created_at\", \"bans\".\"ip_address\", \"bans\".\"updated_at\", \"bans\".\"user_id\"";
  static constexpr int kColumnCount = 5;

  std::int64_t id{};
  std::string_view created_at{};
  std::string_view ip_address{};
  std::string_view updated_at{};
  std::int64_t user_id{};

  [[nodiscard]] static BanRow read(RowReader& r) {
    BanRow row;
    row.id = r.i64(0);
    row.created_at = r.text(1);
    row.ip_address = r.text(2);
    row.updated_at = r.text(3);
    row.user_id = r.i64(4);
    return row;
  }
};

// Table boosts.
struct BoostRow {
  static constexpr Table kTable = Table::Boosts;
  static constexpr std::string_view kTableName = "boosts";
  // The columns to select, in the order that `read` uses.
  static constexpr std::string_view kColumns = "\"boosts\".\"id\", \"boosts\".\"booster_id\", \"boosts\".\"content\", \"boosts\".\"created_at\", \"boosts\".\"message_id\", \"boosts\".\"updated_at\"";
  static constexpr int kColumnCount = 6;

  std::int64_t id{};
  std::int64_t booster_id{};
  std::string_view content{};
  std::string_view created_at{};
  std::int64_t message_id{};
  std::string_view updated_at{};

  [[nodiscard]] static BoostRow read(RowReader& r) {
    BoostRow row;
    row.id = r.i64(0);
    row.booster_id = r.i64(1);
    row.content = r.text(2);
    row.created_at = r.text(3);
    row.message_id = r.i64(4);
    row.updated_at = r.text(5);
    return row;
  }
};

// Table memberships.
struct MembershipRow {
  static constexpr Table kTable = Table::Memberships;
  static constexpr std::string_view kTableName = "memberships";
  // The columns to select, in the order that `read` uses.
  static constexpr std::string_view kColumns = "\"memberships\".\"id\", \"memberships\".\"connected_at\", \"memberships\".\"connections\", \"memberships\".\"created_at\", \"memberships\".\"involvement\", \"memberships\".\"room_id\", \"memberships\".\"unread_at\", \"memberships\".\"updated_at\", \"memberships\".\"user_id\"";
  static constexpr int kColumnCount = 9;

  std::int64_t id{};
  std::optional<std::string_view> connected_at{};
  std::int64_t connections{};
  std::string_view created_at{};
  std::optional<std::string_view> involvement{};
  std::int64_t room_id{};
  std::optional<std::string_view> unread_at{};
  std::string_view updated_at{};
  std::int64_t user_id{};

  [[nodiscard]] static MembershipRow read(RowReader& r) {
    MembershipRow row;
    row.id = r.i64(0);
    row.connected_at = r.text_opt(1);
    row.connections = r.i64(2);
    row.created_at = r.text(3);
    row.involvement = r.text_opt(4);
    row.room_id = r.i64(5);
    row.unread_at = r.text_opt(6);
    row.updated_at = r.text(7);
    row.user_id = r.i64(8);
    return row;
  }
};

// Table messages.
struct MessageRow {
  static constexpr Table kTable = Table::Messages;
  static constexpr std::string_view kTableName = "messages";
  // The columns to select, in the order that `read` uses.
  static constexpr std::string_view kColumns = "\"messages\".\"id\", \"messages\".\"client_message_id\", \"messages\".\"created_at\", \"messages\".\"creator_id\", \"messages\".\"room_id\", \"messages\".\"updated_at\"";
  static constexpr int kColumnCount = 6;

  std::int64_t id{};
  std::string_view client_message_id{};
  std::string_view created_at{};
  std::int64_t creator_id{};
  std::int64_t room_id{};
  std::string_view updated_at{};

  [[nodiscard]] static MessageRow read(RowReader& r) {
    MessageRow row;
    row.id = r.i64(0);
    row.client_message_id = r.text(1);
    row.created_at = r.text(2);
    row.creator_id = r.i64(3);
    row.room_id = r.i64(4);
    row.updated_at = r.text(5);
    return row;
  }
};

// Table push_subscriptions.
struct PushSubscriptionRow {
  static constexpr Table kTable = Table::PushSubscriptions;
  static constexpr std::string_view kTableName = "push_subscriptions";
  // The columns to select, in the order that `read` uses.
  static constexpr std::string_view kColumns = "\"push_subscriptions\".\"id\", \"push_subscriptions\".\"auth_key\", \"push_subscriptions\".\"created_at\", \"push_subscriptions\".\"endpoint\", \"push_subscriptions\".\"p256dh_key\", \"push_subscriptions\".\"updated_at\", \"push_subscriptions\".\"user_agent\", \"push_subscriptions\".\"user_id\"";
  static constexpr int kColumnCount = 8;

  std::int64_t id{};
  std::optional<std::string_view> auth_key{};
  std::string_view created_at{};
  std::optional<std::string_view> endpoint{};
  std::optional<std::string_view> p256dh_key{};
  std::string_view updated_at{};
  std::optional<std::string_view> user_agent{};
  std::int64_t user_id{};

  [[nodiscard]] static PushSubscriptionRow read(RowReader& r) {
    PushSubscriptionRow row;
    row.id = r.i64(0);
    row.auth_key = r.text_opt(1);
    row.created_at = r.text(2);
    row.endpoint = r.text_opt(3);
    row.p256dh_key = r.text_opt(4);
    row.updated_at = r.text(5);
    row.user_agent = r.text_opt(6);
    row.user_id = r.i64(7);
    return row;
  }
};

// Table rooms.
struct RoomRow {
  static constexpr Table kTable = Table::Rooms;
  static constexpr std::string_view kTableName = "rooms";
  // The columns to select, in the order that `read` uses.
  static constexpr std::string_view kColumns = "\"rooms\".\"id\", \"rooms\".\"created_at\", \"rooms\".\"creator_id\", \"rooms\".\"name\", \"rooms\".\"type\", \"rooms\".\"updated_at\"";
  static constexpr int kColumnCount = 6;

  std::int64_t id{};
  std::string_view created_at{};
  std::int64_t creator_id{};
  std::optional<std::string_view> name{};
  std::string_view type{};
  std::string_view updated_at{};

  [[nodiscard]] static RoomRow read(RowReader& r) {
    RoomRow row;
    row.id = r.i64(0);
    row.created_at = r.text(1);
    row.creator_id = r.i64(2);
    row.name = r.text_opt(3);
    row.type = r.text(4);
    row.updated_at = r.text(5);
    return row;
  }
};

// Table searches.
struct SearchRow {
  static constexpr Table kTable = Table::Searches;
  static constexpr std::string_view kTableName = "searches";
  // The columns to select, in the order that `read` uses.
  static constexpr std::string_view kColumns = "\"searches\".\"id\", \"searches\".\"created_at\", \"searches\".\"query\", \"searches\".\"updated_at\", \"searches\".\"user_id\"";
  static constexpr int kColumnCount = 5;

  std::int64_t id{};
  std::string_view created_at{};
  std::string_view query{};
  std::string_view updated_at{};
  std::int64_t user_id{};

  [[nodiscard]] static SearchRow read(RowReader& r) {
    SearchRow row;
    row.id = r.i64(0);
    row.created_at = r.text(1);
    row.query = r.text(2);
    row.updated_at = r.text(3);
    row.user_id = r.i64(4);
    return row;
  }
};

// Table sessions.
struct SessionRow {
  static constexpr Table kTable = Table::Sessions;
  static constexpr std::string_view kTableName = "sessions";
  // The columns to select, in the order that `read` uses.
  static constexpr std::string_view kColumns = "\"sessions\".\"id\", \"sessions\".\"created_at\", \"sessions\".\"ip_address\", \"sessions\".\"last_active_at\", \"sessions\".\"token\", \"sessions\".\"updated_at\", \"sessions\".\"user_agent\", \"sessions\".\"user_id\"";
  static constexpr int kColumnCount = 8;

  std::int64_t id{};
  std::string_view created_at{};
  std::optional<std::string_view> ip_address{};
  std::string_view last_active_at{};
  std::string_view token{};
  std::string_view updated_at{};
  std::optional<std::string_view> user_agent{};
  std::int64_t user_id{};

  [[nodiscard]] static SessionRow read(RowReader& r) {
    SessionRow row;
    row.id = r.i64(0);
    row.created_at = r.text(1);
    row.ip_address = r.text_opt(2);
    row.last_active_at = r.text(3);
    row.token = r.text(4);
    row.updated_at = r.text(5);
    row.user_agent = r.text_opt(6);
    row.user_id = r.i64(7);
    return row;
  }
};

// Table users.
struct UserRow {
  static constexpr Table kTable = Table::Users;
  static constexpr std::string_view kTableName = "users";
  // The columns to select, in the order that `read` uses.
  static constexpr std::string_view kColumns = "\"users\".\"id\", \"users\".\"bio\", \"users\".\"bot_token\", \"users\".\"created_at\", \"users\".\"email_address\", \"users\".\"name\", \"users\".\"password_digest\", \"users\".\"role\", \"users\".\"status\", \"users\".\"updated_at\"";
  static constexpr int kColumnCount = 10;

  std::int64_t id{};
  std::optional<std::string_view> bio{};
  std::optional<std::string_view> bot_token{};
  std::string_view created_at{};
  std::optional<std::string_view> email_address{};
  std::string_view name{};
  std::optional<std::string_view> password_digest{};
  std::int64_t role{};
  std::int64_t status{};
  std::string_view updated_at{};

  [[nodiscard]] static UserRow read(RowReader& r) {
    UserRow row;
    row.id = r.i64(0);
    row.bio = r.text_opt(1);
    row.bot_token = r.text_opt(2);
    row.created_at = r.text(3);
    row.email_address = r.text_opt(4);
    row.name = r.text(5);
    row.password_digest = r.text_opt(6);
    row.role = r.i64(7);
    row.status = r.i64(8);
    row.updated_at = r.text(9);
    return row;
  }
};

// Table webhooks.
struct WebhookRow {
  static constexpr Table kTable = Table::Webhooks;
  static constexpr std::string_view kTableName = "webhooks";
  // The columns to select, in the order that `read` uses.
  static constexpr std::string_view kColumns = "\"webhooks\".\"id\", \"webhooks\".\"created_at\", \"webhooks\".\"updated_at\", \"webhooks\".\"url\", \"webhooks\".\"user_id\"";
  static constexpr int kColumnCount = 5;

  std::int64_t id{};
  std::string_view created_at{};
  std::string_view updated_at{};
  std::optional<std::string_view> url{};
  std::int64_t user_id{};

  [[nodiscard]] static WebhookRow read(RowReader& r) {
    WebhookRow row;
    row.id = r.i64(0);
    row.created_at = r.text(1);
    row.updated_at = r.text(2);
    row.url = r.text_opt(3);
    row.user_id = r.i64(4);
    return row;
  }
};

}  // namespace campfire::db::schema
