# Dumps Marcel's extension, parent and magic tables (after marcel/mime_type/definitions.rb has
# extended them) as C++ for src/storage/marcel_tables.cpp. This is the same source as the Rust
# port's crates/storage/src/tables.rs (reference-tools/storage/dump_tables.rb).
#
# Run it in the reference image, from the repository root:
#   tools/regen_marcel_tables.sh
require "marcel"

# C++ string literal: every byte that is not a letter or digit is a 3-digit octal escape, so a
# following digit never joins the escape.
def cpp_bytes(string)
  body = string.b.bytes.map { |b| (b >= 0x30 && b <= 0x39) || (b >= 0x41 && b <= 0x5a) || (b >= 0x61 && b <= 0x7a) ? b.chr : format("\\%03o", b) }.join
  "std::string_view(\"#{body}\", #{string.bytesize})"
end

$counter = 0
$arrays = []

# Emits the children first, then the array of this level. Returns the array name.
def emit_matches(matches)
  parts = matches.map do |offset, value, children|
    range_start, range_end = offset.is_a?(Range) ? [offset.begin, offset.end] : [offset, -1]
    child_name = children && !children.empty? ? emit_matches(children) : nil
    child_code = child_name ? "std::span<const Match>(#{child_name})" : "std::span<const Match>()"
    value_code = value ? "true, #{cpp_bytes(value)}" : "false, std::string_view()"
    "  {#{range_start}, #{range_end}, #{value_code}, #{child_code}},"
  end
  return nil if parts.empty?
  name = "kMatches#{$counter += 1}"
  $arrays << "constexpr Match #{name}[] = {\n#{parts.join("\n")}\n};"
  name
end

def pairs(table)
  table.sort.map { |a, b| "  {#{cpp_bytes(a)}, #{cpp_bytes(b)}}," }.join("\n")
end

def lists(table)
  names = []
  body = table.sort.map do |type, items|
    name = "kList#{$counter += 1}"
    $arrays << "constexpr std::string_view #{name}[] = {#{items.map { |i| cpp_bytes(i) }.join(", ")}};"
    "  {#{cpp_bytes(type)}, std::span<const std::string_view>(#{name})},"
  end
  body.join("\n")
end

magic = Marcel::MAGIC.map do |type, matches|
  name = emit_matches(matches)
  "  {#{cpp_bytes(type)}, #{name ? "std::span<const Match>(#{name})" : "std::span<const Match>()"}},"
end.join("\n")
type_exts = lists(Marcel::TYPE_EXTS)
type_parents = lists(Marcel::TYPE_PARENTS)

puts "// @generated by src/storage/tools/dump_marcel_tables.rb from marcel #{Marcel::VERSION}."
puts "// Do not edit by hand. Regenerate with tools/regen_marcel_tables.sh."
puts "// clang-format off"
puts '#include "storage/marcel_tables.hpp"'
puts
puts "namespace campfire::storage::marcel_tables {"
puts "namespace {"
puts $arrays.join("\n")
puts
puts "constexpr std::pair<std::string_view, std::string_view> kExtensionsData[] = {\n#{pairs(Marcel::EXTENSIONS)}\n};"
puts "constexpr std::pair<std::string_view, std::span<const std::string_view>> kTypeExtsData[] = {\n#{type_exts}\n};"
puts "constexpr std::pair<std::string_view, std::span<const std::string_view>> kTypeParentsData[] = {\n#{type_parents}\n};"
puts "constexpr std::pair<std::string_view, std::span<const Match>> kMagicData[] = {\n#{magic}\n};"
puts "}  // namespace"
puts
puts "const std::span<const std::pair<std::string_view, std::string_view>> kExtensions(kExtensionsData);"
puts "const std::span<const std::pair<std::string_view, std::span<const std::string_view>>> kTypeExts(kTypeExtsData);"
puts "const std::span<const std::pair<std::string_view, std::span<const std::string_view>>> kTypeParents(kTypeParentsData);"
puts "const std::span<const std::pair<std::string_view, std::span<const Match>>> kMagic(kMagicData);"
puts "}  // namespace campfire::storage::marcel_tables"
