#!/usr/bin/env python3
"""Embed files in a C++ source. Usage: embed.py OUT.cpp FILE... (build time, no #embed needed).

Each file "dir/404.html.gz" becomes `campfire::app::data::f_404_html_gz`, a std::string_view.
"""
import os
import re
import sys


def main():
    out, files = sys.argv[1], sys.argv[2:]
    lines = ["// Generated by tools/embed.py. Do not edit.", "#include \"app/data.hpp\"", "",
             "namespace campfire::app::data {"]
    for path in files:
        name = "f_" + re.sub(r"[^A-Za-z0-9]", "_", os.path.basename(path))
        data = open(path, "rb").read()
        lines.append("static const unsigned char k_%s[] = {" % name)
        for i in range(0, len(data), 24):
            lines.append("    " + ",".join(str(b) for b in data[i:i + 24]) + ",")
        if not data:
            lines.append("    0,")
        lines.append("};")
        lines.append("const std::string_view %s{reinterpret_cast<const char*>(k_%s), %d};" % (name, name, len(data)))
    lines.append("}  // namespace campfire::app::data")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
