#!/usr/bin/env python3
"""Generate the C++ route table from src/app/routes/<area>.inc files.

Rails: config/routes.rb. Format of a line (blank lines and "#" comments are allowed):

    METHOD  /pattern/with/:params(.:format)  namespace::handler  [name=value ...]

- METHOD is GET, HEAD, POST, PUT, PATCH, DELETE or OPTIONS.
- A segment is a literal ("messages"), a parameter (":room_id"), a literal prefix and a parameter
  ("@:message_id"), or a glob that takes the rest of the path ("*filename", last segment only).
- A parameter has one or more characters and no ".". "(.:format)" at the end of the pattern
  allows a ".ext" suffix on the last segment and sets the parameter "format".
- The handler "a::b" is the function `campfire::routes::a::b`, of the type
  `Task<net::Response>(net::Ctx&)`.
- "name=value" sets a default parameter value (Rails `defaults:`).

The routes keep the order of the input files (sorted by name), then the order of the lines. The
first route that matches wins, as in Rails.
"""
import argparse
import re
import sys

METHODS = ["GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]  # order of enum Method
IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


class RouteError(Exception):
    pass


def cxx_string(text):
    out = []
    for ch in text:
        if ch in '"\\':
            out.append("\\" + ch)
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            raise RouteError("non-ASCII text in " + repr(text))
    return '"' + "".join(out) + '"'


def parse_segments(pattern):
    if not pattern.startswith("/"):
        raise RouteError("pattern must start with '/': " + pattern)
    fmt = False
    if pattern.endswith("(.:format)"):
        fmt = True
        pattern = pattern[: -len("(.:format)")]
    if "(" in pattern or ")" in pattern:
        raise RouteError("only (.:format) at the end is allowed: " + pattern)
    parts = [p for p in pattern.split("/")[1:]]
    if parts == [""]:
        parts = []
    segments, names = [], set()
    for i, part in enumerate(parts):
        if part == "":
            raise RouteError("empty segment in " + pattern)
        if part.startswith("*"):
            kind, text, name = "Glob", "", part[1:]
            if i != len(parts) - 1:
                raise RouteError("a glob must be the last segment: " + pattern)
            if fmt:
                raise RouteError("a glob takes no format: " + pattern)
        elif ":" in part:
            text, _, name = part.partition(":")
            kind = "Prefixed" if text else "Param"
        else:
            kind, text, name = "Literal", part, ""
        if kind != "Literal":
            if not IDENT.match(name) or name == "format":
                raise RouteError("bad parameter name '%s' in %s" % (name, pattern))
            if name in names:
                raise RouteError("duplicate parameter '%s' in %s" % (name, pattern))
            names.add(name)
        segments.append((kind, text, name))
    if fmt and not segments:
        raise RouteError("the root route takes no format")
    return segments, fmt


def parse_file(path, routes):
    with open(path, encoding="utf-8") as f:
        for number, line in enumerate(f, 1):
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            where = "%s:%d" % (path, number)
            fields = line.split()
            if len(fields) < 3:
                raise RouteError(where + ": expected METHOD PATTERN HANDLER")
            method, pattern, handler = fields[:3]
            if method not in METHODS:
                raise RouteError(where + ": unknown method " + method)
            if not all(IDENT.match(p) for p in handler.split("::")):
                raise RouteError(where + ": bad handler " + handler)
            defaults = []
            for item in fields[3:]:
                name, eq, value = item.partition("=")
                if not eq or not IDENT.match(name):
                    raise RouteError(where + ": bad default " + item)
                defaults.append((name, value))
            try:
                segments, fmt = parse_segments(pattern)
            except RouteError as error:
                raise RouteError(where + ": " + str(error))
            routes.append(dict(method=method, pattern=pattern, handler=handler, segments=segments,
                               format=fmt, defaults=defaults))


def span(array_name, count, element):
    if count == 0:
        return "std::span<const %s>{}" % element
    return "std::span<const %s>(%s)" % (element, array_name)


def generate(routes, namespace, function):
    out = ["// Generated by tools/routes_gen.py. Do not edit.", '#include "core/task.hpp"',
           '#include "net/ctx.hpp"', '#include "net/router.hpp"', "", "#include <cstdint>", ""]
    # Forward declarations of the handlers.
    tree = {}
    for r in routes:
        *spaces, fn = r["handler"].split("::")
        tree.setdefault(tuple(spaces), set()).add(fn)
    for spaces, names in sorted(tree.items()):
        opening = "namespace campfire::routes" + "".join("::" + s for s in spaces) + " {"
        out.append(opening)
        for fn in sorted(names):
            out.append("campfire::Task<campfire::net::Response> %s(campfire::net::Ctx&);" % fn)
        out.append("}")
    out += ["", "namespace {", "using namespace campfire::net;", ""]
    for i, r in enumerate(routes):
        if r["segments"]:
            items = ", ".join("{SegmentKind::%s, %s, %s}" % (k, cxx_string(t), cxx_string(n))
                              for k, t, n in r["segments"])
            out.append("constexpr Segment kSeg%d[] = {%s};" % (i, items))
        if r["defaults"]:
            items = ", ".join("{%s, %s}" % (cxx_string(n), cxx_string(v)) for n, v in r["defaults"])
            out.append("constexpr RouteDefault kDef%d[] = {%s};" % (i, items))
    out.append("")
    out.append("constexpr Route kRoutes[] = {")
    for i, r in enumerate(routes):
        handler = "campfire::routes::" + r["handler"]
        out.append("    {Method::%s, &%s, %s, %s, %s, %s, %s}," % (
            r["method"].capitalize(), handler, cxx_string(r["handler"]), cxx_string(r["pattern"]),
            span("kSeg%d" % i, len(r["segments"]), "Segment"), "true" if r["format"] else "false",
            span("kDef%d" % i, len(r["defaults"]), "RouteDefault")))
    if not routes:
        out.append("    // no routes")
    out.append("};")
    out.append("")

    def key_of(r):
        first = r["segments"][0] if r["segments"] else None
        if first is None:
            return "root"
        if first[0] == "Literal":
            return ("key", first[1].split(".", 1)[0])
        return "dynamic"

    index_lines = []
    for m, method in enumerate(METHODS):
        mine = [(i, r) for i, r in enumerate(routes) if r["method"] == method]
        root = [i for i, r in mine if key_of(r) == "root"]
        dynamic = [i for i, r in mine if key_of(r) == "dynamic"]
        keys = sorted({key_of(r)[1] for _, r in mine if isinstance(key_of(r), tuple)})
        buckets = []
        for k in keys:
            ids = [i for i, r in mine if key_of(r) == "dynamic" or key_of(r) == ("key", k)]
            buckets.append((k, ids))

        def ids_array(name, ids):
            out.append("constexpr std::uint16_t %s[] = {%s};" % (name, ", ".join(str(i) for i in ids)))
            return "std::span<const std::uint16_t>(%s)" % name

        empty = "std::span<const std::uint16_t>{}"
        root_expr = ids_array("kRoot%d" % m, root) if root else empty
        fall_expr = ids_array("kFall%d" % m, dynamic) if dynamic else empty
        items = []
        for b, (k, ids) in enumerate(buckets):
            items.append("{%s, %s}" % (cxx_string(k), ids_array("kB%d_%d" % (m, b), ids)))
        if items:
            out.append("constexpr Bucket kBuckets%d[] = {%s};" % (m, ", ".join(items)))
            b_expr = "std::span<const Bucket>(kBuckets%d)" % m
        else:
            b_expr = "std::span<const Bucket>{}"
        index_lines.append("    MethodIndex{%s, %s, %s}," % (b_expr, fall_expr, root_expr))
    out.append("")
    out.append("constexpr RouteTable kTable = {")
    out.append("    std::span<const Route>(kRoutes, %d)," % len(routes))
    out.append("    {{")
    out += index_lines
    out.append("    MethodIndex{},")  # Method::Other has no routes
    out.append("    }},")
    out.append("};")
    out.append("}  // namespace")
    out.append("")
    out.append("namespace %s {" % namespace)
    out.append("const campfire::net::RouteTable& %s() { return kTable; }" % function)
    out.append("}  // namespace %s" % namespace)
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--namespace", default="campfire::app")
    ap.add_argument("--function", default="routes")
    ap.add_argument("inputs", nargs="*")
    args = ap.parse_args()
    routes = []
    try:
        for path in sorted(args.inputs):
            parse_file(path, routes)
    except RouteError as error:
        print("routes_gen: " + str(error), file=sys.stderr)
        return 1
    if len(routes) >= 65535:
        print("routes_gen: too many routes", file=sys.stderr)
        return 1
    text = generate(routes, args.namespace, args.function)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
