#!/usr/bin/env python3
"""Generates src/db/schema.gen.hpp from spec/schema.rb (Rails: db/schema.rb).

Usage: schema_gen.py <schema.rb> <output.hpp>

For each table the output has a row struct, the column list for SELECT, and a reader that
copies the columns of the current row into the request arena.
"""
import re
import sys

KEYWORDS = {"class", "default", "delete", "new", "operator", "template", "this", "union", "namespace", "new"}

TYPES = {
    "integer": ("std::int64_t", "i64"),
    "bigint": ("std::int64_t", "i64"),
    "boolean": ("bool", "boolean"),
    "float": ("double", "f64"),
    "decimal": ("double", "f64"),
    "string": ("std::string_view", "text"),
    "text": ("std::string_view", "text"),
    "json": ("std::string_view", "text"),
    "datetime": ("std::string_view", "text"),
    "date": ("std::string_view", "text"),
    "time": ("std::string_view", "text"),
    "binary": ("std::string_view", "text"),
}


def camel(name):
    return "".join(part.capitalize() for part in name.split("_"))


def singular(name):
    if name.endswith("ches") or name.endswith("shes") or name.endswith("sses") or name.endswith("xes"):
        return name[:-2]
    if name.endswith("ies"):
        return name[:-3] + "y"
    return name[:-1] if name.endswith("s") else name


def parse(text):
    tables = []
    current = None
    for line in text.splitlines():
        line = line.strip()
        m = re.match(r'create_table "(\w+)"(.*) do \|t\|', line)
        if m:
            current = {"name": m.group(1), "columns": [], "id": 'id: false' not in m.group(2)}
            tables.append(current)
            continue
        if line == "end":
            current = None
            continue
        if current is None:
            continue
        m = re.match(r't\.(\w+) "(\w+)"(.*)$', line)
        if m and m.group(1) != "index":
            kind, name, rest = m.groups()
            if kind not in TYPES:
                raise SystemExit(f"schema_gen: unknown column type {kind} in {current['name']}.{name}")
            current["columns"].append({"name": name, "kind": kind, "null": "null: false" not in rest})
    return tables


def member(name):
    return name + "_" if name in KEYWORDS else name


def emit(tables):
    out = []
    w = out.append
    w("// clang-format off")
    w("// Generated by tools/schema_gen.py from spec/schema.rb (Rails: db/schema.rb). Do not edit.")
    w("#pragma once")
    w("")
    w("#include <cstddef>")
    w("#include <cstdint>")
    w("#include <optional>")
    w("#include <string_view>")
    w("")
    w('#include "db/row.hpp"')
    w("")
    w("namespace campfire::db::schema {")
    w("")
    w("enum class Table : std::uint8_t {")
    for t in tables:
        w(f"  {camel(t['name'])},")
    w("};")
    w("inline constexpr std::size_t kTableCount = %d;" % len(tables))
    w("")
    w("[[nodiscard]] constexpr std::string_view table_name(Table table) noexcept {")
    w("  switch (table) {")
    for t in tables:
        w(f'    case Table::{camel(t["name"])}: return "{t["name"]}";')
    w("  }")
    w('  return "";')
    w("}")
    w("")
    for t in tables:
        cols = []
        if t["id"]:
            cols.append({"name": "id", "kind": "bigint", "null": False})
        cols += t["columns"]
        sname = camel(singular(t["name"])) + "Row"
        w(f"// Table {t['name']}.")
        w(f"struct {sname} {{")
        w(f"  static constexpr Table kTable = Table::{camel(t['name'])};")
        w(f'  static constexpr std::string_view kTableName = "{t["name"]}";')
        select = ", ".join(f'\\"{t["name"]}\\".\\"{c["name"]}\\"' for c in cols)
        w(f'  // The columns to select, in the order that `read` uses.')
        w(f'  static constexpr std::string_view kColumns = "{select}";')
        w(f"  static constexpr int kColumnCount = {len(cols)};")
        w("")
        for c in cols:
            ctype, _ = TYPES[c["kind"]]
            if c["null"]:
                ctype = f"std::optional<{ctype}>"
            w(f"  {ctype} {member(c['name'])}{{}};")
        w("")
        w(f"  [[nodiscard]] static {sname} read(RowReader& r) {{")
        w(f"    {sname} row;")
        for i, c in enumerate(cols):
            _, fn = TYPES[c["kind"]]
            suffix = "_opt" if c["null"] else ""
            w(f"    row.{member(c['name'])} = r.{fn}{suffix}({i});")
        w("    return row;")
        w("  }")
        w("};")
        w("")
    w("}  // namespace campfire::db::schema")
    return "\n".join(out) + "\n"


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    with open(sys.argv[1], encoding="utf-8") as f:
        tables = parse(f.read())
    text = emit(tables)
    try:
        with open(sys.argv[2], encoding="utf-8") as f:
            if f.read() == text:
                return
    except FileNotFoundError:
        pass
    with open(sys.argv[2], "w", encoding="utf-8") as f:
        f.write(text)


main()
